name: Set Up Project

runs:
  using: 'composite'
  steps:
    - name: 'Derive appropriate SHAs for base and head for `nx affected` commands'
      uses: nrwl/nx-set-shas@dbe0650947e5f2c81f59190a38512cf49126fe6b # v4

    - name: 'Setup Node'
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: 'Cache dependencies'
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: 'Install dependencies'
      shell: bash
      run: yarn install --immutable
