export const GITHUB_ENDPOINT = process?.env?.NEXT_PUBLIC_GITHUB_GQL_ENDPOINT || "MISSING_GITHUB_GQL_ENDPOINT";

export const GITHUB_TOKEN = process?.env?.NEXT_PUBLIC_GITHUB_TOKEN || "MISSING_GITHUB_TOKEN";
