name: '🧪 CI'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: 'Set up project'
        uses: ./.github/actions/setup-project

#      - name: 'Format Check'
#        run: yarn run nx affected --target=format:check --parallel --max-parallel=2

#      - name: 'Lint'
#        run: yarn run nx affected --target=lint --parallel --max-parallel=2

      - name: 'Build'
        run: yarn run build
